#Thanks to https://github.com/docker/awesome-compose/blob/master/spring-postgres/docker-compose.yaml
#https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
version: "3.5"
services:

  frontend:
    depends_on:
      - backend
    image: jlmacle/atl-front-end:v0.9
    ports:
      - 80:80     
    expose:
      - 80  
    networks:
     - atl-network
     
  postgresql:
    image: postgres:alpine    
    networks:
      - atl-network     
    environment:
      # https://hub.docker.com/_/postgres
      # "The PostgreSQL image uses several environment variables which are easy to miss. 
      # The only variable required is POSTGRES_PASSWORD, the rest are optional.
      # Warning: the Docker specific variables will only have an effect if you start the container with a data directory that is empty; 
      # any pre-existing database will be left untouched on container startup.      
      - POSTGRES_PASSWORD=test    
  
  backend:
    depends_on:
      - postgresql
    image: jlmacle/atl-back-end:v0.9
    ports:
      - 8080:8080    
    environment:
      - DB_URL=jdbc:postgresql://postgresql:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
    networks:
      - atl-network  
  
networks:
  atl-network: {}
